const sharedColors = {
  primary: "#20AB6E",
  lime: "#D7FFD4",
  pink: "#F655FF",
  red: "#E32326",
  redLight: "#FFE9E9",
  brown: "#29271D",
  sky: "#E5EDFF",
  teal: "#0E4D45",
  yellow: "#FCBB80",
  orange: "#EF580B",
  blue: "#239FE3",
  blueLight: "#E9F8FF",
  green: "#199A48",
  greenLight: "#ECFFE9",
  grey: "#7c7c7c",
  greyLight: "#E5E5E5",
  greyDark: "#242026",
  input: "#EEE9F0",
  selected: "#F7F2F9",
  white: "#FFFFFF",
  black: "#000000",
} as const;

export default {
  ...sharedColors,
  light: {
    text: sharedColors.black,
    background: sharedColors.white,
    tint: sharedColors.blueLight,
    tabIconDefault: sharedColors.greyDark,
    tabIconSelected: sharedColors.blue,
    border: sharedColors.greyLight,
    ...sharedColors,
  },
};
